ALTER TABLE "SeoSettings" ADD COLUMN "countryCode" TEXT NOT NULL DEFAULT 'IN';
ALTER TABLE "SeoSettings" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "SeoSettings" ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'en-IN';
ALTER TABLE "SeoSettings" ADD COLUMN "phoneCountryCode" TEXT NOT NULL DEFAULT '+91';
